import type { RecommendedSource } from './types'

export const RECOMMENDED_SOURCES: RecommendedSource[] = [
  // Français
  { type: 'rss', name: 'Numerama', url: 'https://www.numerama.com/feed/', category: 'Tech', lang: 'fr' },
  { type: 'rss', name: 'Le Monde Informatique', url: 'https://www.lemondeinformatique.fr/flux-rss/thematique/toutes-les-actualites/rss.xml', category: 'Tech', lang: 'fr' },
  { type: 'rss', name: 'Korben', url: 'https://korben.info/feed', category: 'Dev', lang: 'fr' },
  { type: 'rss', name: 'LinuxFr', url: 'https://linuxfr.org/news.atom', category: 'Dev', lang: 'fr' },
  { type: 'rss', name: '01net', url: 'https://www.01net.com/actualites/feed/', category: 'Tech', lang: 'fr' },
  { type: 'rss', name: 'Génération-NT', url: 'https://www.generation-nt.com/export/rss.xml', category: 'Tech', lang: 'fr' },
  { type: 'rss', name: 'Clubic', url: 'https://www.clubic.com/feed/rss', category: 'Tech', lang: 'fr' },
  { type: 'rss', name: 'Frandroid', url: 'https://www.frandroid.com/feed', category: 'Mobile', lang: 'fr' },
  { type: 'rss', name: 'Les Numériques', url: 'https://www.lesnumeriques.com/rss.xml', category: 'Tech', lang: 'fr' },
  { type: 'rss', name: 'Developpez.com', url: 'https://www.developpez.com/index/rss', category: 'Dev', lang: 'fr' },
  { type: 'rss', name: 'ZDNet France', url: 'https://www.zdnet.fr/feeds/rss/actualites/', category: 'Tech', lang: 'fr' },
  { type: 'rss', name: 'Journal du Geek', url: 'https://www.journaldugeek.com/feed/', category: 'Tech', lang: 'fr' },
  { type: 'rss', name: 'Presse-citron', url: 'https://www.presse-citron.net/feed/', category: 'Tech', lang: 'fr' },
  { type: 'rss', name: 'Next', url: 'https://next.ink/feed/', category: 'Tech', lang: 'fr' },
  { type: 'rss', name: 'Silicon.fr', url: 'https://www.silicon.fr/feed', category: 'Dev', lang: 'fr' },
  { type: 'rss', name: "Tom's Hardware FR", url: 'https://www.tomshardware.fr/feed/', category: 'Tech', lang: 'fr' },
  { type: 'rss', name: 'Phonandroid', url: 'https://www.phonandroid.com/feed', category: 'Mobile', lang: 'fr' },
  { type: 'rss', name: 'Siècle Digital', url: 'https://siecledigital.fr/feed/', category: 'Tech', lang: 'fr' },
  { type: 'rss', name: 'Gamekult', url: 'https://www.gamekult.com/feed.xml', category: 'Jeux vidéo', lang: 'fr' },
  { type: 'rss', name: 'Jeuxvideo.com', url: 'https://www.jeuxvideo.com/rss/rss.xml', category: 'Jeux vidéo', lang: 'fr' },
  { type: 'rss', name: 'Futura Sciences', url: 'https://www.futura-sciences.com/rss/actualites.xml', category: 'Science', lang: 'fr' },
  { type: 'rss', name: 'Sciences et Avenir', url: 'https://www.sciencesetavenir.fr/rss.xml', category: 'Science', lang: 'fr' },
  { type: 'reddit', name: 'r/france (tech)', url: 'https://www.reddit.com/r/france/.rss', category: 'Général', lang: 'fr' },
  // Anglais
  { type: 'hackernews', name: 'Hacker News (front page)', url: '', category: 'Général', lang: 'en' },
  { type: 'rss', name: 'The Verge', url: 'https://www.theverge.com/rss/index.xml', category: 'Tech', lang: 'en' },
  { type: 'rss', name: 'Ars Technica', url: 'https://feeds.arstechnica.com/arstechnica/index', category: 'Tech', lang: 'en' },
  { type: 'rss', name: 'TechCrunch', url: 'https://techcrunch.com/feed/', category: 'Tech', lang: 'en' },
  { type: 'rss', name: 'Wired', url: 'https://www.wired.com/feed/rss', category: 'Tech', lang: 'en' },
  { type: 'rss', name: 'Engadget', url: 'https://www.engadget.com/rss.xml', category: 'Tech', lang: 'en' },
  { type: 'rss', name: 'TechRadar', url: 'https://www.techradar.com/rss', category: 'Tech', lang: 'en' },
  { type: 'rss', name: 'VentureBeat', url: 'https://venturebeat.com/feed/', category: 'Tech', lang: 'en' },
  { type: 'rss', name: 'The Register', url: 'https://www.theregister.com/headlines.atom', category: 'Tech', lang: 'en' },
  { type: 'rss', name: 'MIT Technology Review', url: 'https://www.technologyreview.com/feed/', category: 'Tech', lang: 'en' },
  { type: 'rss', name: 'Slashdot', url: 'https://rss.slashdot.org/Slashdot/slashdotMain', category: 'Général', lang: 'en' },
  { type: 'reddit', name: 'r/technology', url: 'https://www.reddit.com/r/technology/.rss', category: 'Général', lang: 'en' },
  { type: 'reddit', name: 'r/programming', url: 'https://www.reddit.com/r/programming/.rss', category: 'Dev', lang: 'en' },
  // Développement (anglais)
  { type: 'rss', name: 'GitHub Blog', url: 'https://github.blog/feed/', category: 'Dev', lang: 'en' },
  { type: 'rss', name: 'Stack Overflow Blog', url: 'https://stackoverflow.blog/feed/', category: 'Dev', lang: 'en' },
  { type: 'rss', name: 'Dev.to', url: 'https://dev.to/feed', category: 'Dev', lang: 'en' },
  { type: 'rss', name: 'InfoQ', url: 'https://feed.infoq.com/', category: 'Dev', lang: 'en' },
  { type: 'rss', name: 'Smashing Magazine', url: 'https://www.smashingmagazine.com/feed/', category: 'Dev', lang: 'en' },
  { type: 'rss', name: 'CSS-Tricks', url: 'https://css-tricks.com/feed/', category: 'Dev', lang: 'en' },
  { type: 'reddit', name: 'r/webdev', url: 'https://www.reddit.com/r/webdev/.rss', category: 'Dev', lang: 'en' },
  { type: 'reddit', name: 'r/selfhosted', url: 'https://www.reddit.com/r/selfhosted/.rss', category: 'Dev', lang: 'en' },
  // Sécurité (anglais)
  { type: 'rss', name: 'Krebs on Security', url: 'https://krebsonsecurity.com/feed/', category: 'Sécurité', lang: 'en' },
  { type: 'rss', name: 'The Hacker News', url: 'https://feeds.feedburner.com/TheHackersNews', category: 'Sécurité', lang: 'en' },
  { type: 'rss', name: 'BleepingComputer', url: 'https://www.bleepingcomputer.com/feed/', category: 'Sécurité', lang: 'en' },
  { type: 'rss', name: 'Schneier on Security', url: 'https://www.schneier.com/feed/atom/', category: 'Sécurité', lang: 'en' },
  { type: 'reddit', name: 'r/netsec', url: 'https://www.reddit.com/r/netsec/.rss', category: 'Sécurité', lang: 'en' },
  // IA (anglais)
  { type: 'rss', name: 'Hugging Face', url: 'https://huggingface.co/blog/feed.xml', category: 'IA', lang: 'en' },
  { type: 'reddit', name: 'r/MachineLearning', url: 'https://www.reddit.com/r/MachineLearning/.rss', category: 'IA', lang: 'en' },
  // Cloud / DevOps (anglais)
  { type: 'rss', name: 'AWS Blog', url: 'https://aws.amazon.com/blogs/aws/feed/', category: 'Cloud', lang: 'en' },
  { type: 'rss', name: 'Kubernetes Blog', url: 'https://kubernetes.io/feed.xml', category: 'Cloud', lang: 'en' },
  { type: 'rss', name: 'Docker Blog', url: 'https://www.docker.com/blog/feed/', category: 'Cloud', lang: 'en' },
  { type: 'rss', name: 'The New Stack', url: 'https://thenewstack.io/feed/', category: 'Cloud', lang: 'en' },
  { type: 'rss', name: 'DevOps.com', url: 'https://devops.com/feed/', category: 'Cloud', lang: 'en' },
  { type: 'reddit', name: 'r/devops', url: 'https://www.reddit.com/r/devops/.rss', category: 'Cloud', lang: 'en' },
  { type: 'reddit', name: 'r/kubernetes', url: 'https://www.reddit.com/r/kubernetes/.rss', category: 'Cloud', lang: 'en' },
  // Hardware (anglais)
  { type: 'rss', name: "Tom's Hardware", url: 'https://www.tomshardware.com/feeds/all', category: 'Hardware', lang: 'en' },
  { type: 'rss', name: 'Phoronix', url: 'https://www.phoronix.com/rss.php', category: 'Hardware', lang: 'en' },
  { type: 'reddit', name: 'r/hardware', url: 'https://www.reddit.com/r/hardware/.rss', category: 'Hardware', lang: 'en' },
  // Crypto (anglais)
  { type: 'rss', name: 'CoinDesk', url: 'https://www.coindesk.com/arc/outboundfeeds/rss/', category: 'Crypto', lang: 'en' },
  { type: 'rss', name: 'Cointelegraph', url: 'https://cointelegraph.com/rss', category: 'Crypto', lang: 'en' },
  { type: 'rss', name: 'Decrypt', url: 'https://decrypt.co/feed', category: 'Crypto', lang: 'en' },
  // Jeux vidéo (anglais)
  { type: 'rss', name: 'Polygon', url: 'https://www.polygon.com/rss/index.xml', category: 'Jeux vidéo', lang: 'en' },
  { type: 'rss', name: 'Eurogamer', url: 'https://www.eurogamer.net/feed', category: 'Jeux vidéo', lang: 'en' },
  { type: 'rss', name: 'PC Gamer', url: 'https://www.pcgamer.com/rss/', category: 'Jeux vidéo', lang: 'en' },
  // Science (anglais)
  { type: 'rss', name: 'ScienceDaily', url: 'https://www.sciencedaily.com/rss/all.xml', category: 'Science', lang: 'en' },
  { type: 'rss', name: 'Quanta Magazine', url: 'https://www.quantamagazine.org/feed/', category: 'Science', lang: 'en' },
  // Espagnol
  { type: 'rss', name: 'Xataka', url: 'https://www.xataka.com/index.xml', category: 'Tech', lang: 'es' },
  { type: 'rss', name: 'Genbeta', url: 'https://www.genbeta.com/index.xml', category: 'Dev', lang: 'es' },
  { type: 'rss', name: 'Hipertextual', url: 'https://hipertextual.com/feed', category: 'Tech', lang: 'es' },
  { type: 'rss', name: 'MuyComputer', url: 'https://www.muycomputer.com/feed/', category: 'Tech', lang: 'es' },
  { type: 'rss', name: 'ADSLZone', url: 'https://www.adslzone.net/feed/', category: 'Tech', lang: 'es' },
  { type: 'rss', name: 'Xataka Android', url: 'https://www.xatakandroid.com/index.xml', category: 'Mobile', lang: 'es' },
  { type: 'rss', name: 'FayerWayer', url: 'https://www.fayerwayer.com/feed/', category: 'Tech', lang: 'es' },
  // Allemand
  { type: 'rss', name: 'heise online', url: 'https://www.heise.de/rss/heise-atom.xml', category: 'Tech', lang: 'de' },
  { type: 'rss', name: 'Golem.de', url: 'https://rss.golem.de/rss.php?feed=RSS2.0', category: 'Tech', lang: 'de' },
  { type: 'rss', name: 't3n', url: 'https://t3n.de/rss.xml', category: 'Tech', lang: 'de' },
  { type: 'rss', name: 'ComputerBase', url: 'https://www.computerbase.de/rss/news.xml', category: 'Tech', lang: 'de' },
  { type: 'rss', name: 'Caschys Blog', url: 'https://stadt-bremerhaven.de/feed/', category: 'Tech', lang: 'de' },
  { type: 'rss', name: 'netzpolitik.org', url: 'https://netzpolitik.org/feed/', category: 'Général', lang: 'de' },
  { type: 'rss', name: 'WinFuture', url: 'https://static.winfuture.de/feeds/WinFuture-News-rss2.0.xml', category: 'Tech', lang: 'de' },
  // Italien
  { type: 'rss', name: 'Punto Informatico', url: 'https://www.punto-informatico.it/feed/', category: 'Tech', lang: 'it' },
  { type: 'rss', name: 'HTML.it', url: 'https://www.html.it/feed/', category: 'Dev', lang: 'it' },
  { type: 'rss', name: 'DDay.it', url: 'https://www.dday.it/rss', category: 'Tech', lang: 'it' },
  { type: 'rss', name: 'TuttoAndroid', url: 'https://www.tuttoandroid.net/feed/', category: 'Mobile', lang: 'it' },
  { type: 'rss', name: 'Wired Italia', url: 'https://www.wired.it/feed/rss', category: 'Tech', lang: 'it' },
  { type: 'rss', name: 'HDblog', url: 'https://www.hdblog.it/feed/', category: 'Mobile', lang: 'it' },
  // Portugais
  { type: 'rss', name: 'Tecnoblog', url: 'https://tecnoblog.net/feed/', category: 'Tech', lang: 'pt' },
  { type: 'rss', name: 'Olhar Digital', url: 'https://olhardigital.com.br/feed/', category: 'Tech', lang: 'pt' },
  { type: 'rss', name: 'Canaltech', url: 'https://canaltech.com.br/rss/', category: 'Tech', lang: 'pt' },
  { type: 'rss', name: 'Pplware', url: 'https://pplware.sapo.pt/feed/', category: 'Tech', lang: 'pt' }
]
